#!/usr/bin/env python3
"""Stop NetworkManager from putting DHCP on the static camera/spare NICs.

NetworkManager auto-creates a DHCP "Wired connection N" profile for any Ethernet port that
has no profile. On the camera network (static IPs) that must never happen. For every NIC
in hosts/<hostname>/config.yml with role camera or spare, this:

  1. writes /etc/NetworkManager/conf.d/90-pancakebatter-no-auto-default.conf, listing those
     NICs' MAC addresses under no-auto-default (so no default profile is ever created,
     even before the NIC is renamed), and reloads NetworkManager's config;
  2. deletes the generic "Wired connection N" profiles already created for those NICs.

Management/unknown NICs (e.g. the SSH port) are never listed and their profiles are never
deleted. Profiles that this repo created (named after the interface) are never deleted.
The config is the source of truth: re-run after changing roles.

    ./disable_nm_autodhcp.py --dry-run     # show what would change; no root needed
    sudo ./disable_nm_autodhcp.py
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable

import yaml

import hostconfig

CONF_PATH = Path("/etc/NetworkManager/conf.d/90-pancakebatter-no-auto-default.conf")
STATIC_ROLES = {"camera", "spare"}
GENERIC_NAME = re.compile(r"^Wired connection \d+$")

Runner = Callable[[list[str]], str]


def run_nmcli(args: list[str]) -> str:
    res = subprocess.run(["nmcli", *args], capture_output=True, text=True, check=False)
    if res.returncode != 0:
        raise RuntimeError(f"nmcli {' '.join(args)}: {res.stderr.strip()}")
    return res.stdout


def static_nics(config: dict[str, Any]) -> dict[str, str]:
    """{interface name: lowercase MAC} for every camera/spare NIC."""
    out = {}
    for item in config.get("nics", []):
        (name, nic), = item.items()
        if nic.get("role") in STATIC_ROLES and nic.get("mac_address"):
            out[name] = str(nic["mac_address"]).lower()
    return out


def conf_text(nics: dict[str, str], config_path: Path) -> str:
    return (
        f"# Generated by disable_nm_autodhcp.py from {config_path}. Do not edit; re-run the script.\n"
        "# Camera/spare NICs use static IPs: never let NetworkManager create a DHCP profile for them.\n"
        "[main]\n"
        f"no-auto-default+={','.join(sorted(nics.values()))}\n"
    )


def generic_profiles_to_delete(nics: dict[str, str], nmcli: Runner = run_nmcli) -> list[tuple[str, str, str]]:
    """(uuid, name, why) for auto-created 'Wired connection N' profiles bound to our NICs."""
    macs = set(nics.values())
    names = set(nics)
    found = []
    for line in nmcli(["-t", "-f", "NAME,UUID,TYPE", "connection", "show"]).splitlines():
        parts = line.rsplit(":", 2)
        if len(parts) != 3:
            continue
        name, uuid, ctype = parts
        if ctype != "802-3-ethernet" or not GENERIC_NAME.match(name):
            continue
        iface = nmcli(["-g", "connection.interface-name", "connection", "show", "uuid", uuid]).strip()
        mac = nmcli(["-g", "802-3-ethernet.mac-address", "connection", "show", "uuid", uuid]).strip().lower()
        if iface in names:
            found.append((uuid, name, f"bound to {iface}"))
        elif mac in macs:
            found.append((uuid, name, f"bound to MAC {mac}"))
    return found


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="show what would change; write and delete nothing")
    ap.add_argument("--config", type=Path, default=hostconfig.default_config_path())
    ap.add_argument("--conf-path", type=Path, default=CONF_PATH, help=argparse.SUPPRESS)
    args = ap.parse_args(argv)

    if not args.dry_run and os.geteuid() != 0:
        raise SystemExit("run with sudo (or use --dry-run)")
    try:
        config = yaml.safe_load(args.config.read_text())
    except OSError as exc:
        raise SystemExit(f"cannot read config: {exc}")
    nics = static_nics(config)
    if not nics:
        raise SystemExit("no camera/spare NICs in the config; nothing to do")

    text = conf_text(nics, args.config)
    try:
        victims = generic_profiles_to_delete(nics)
    except (RuntimeError, OSError) as exc:
        raise SystemExit(f"cannot list NetworkManager profiles: {exc}")

    print(f"NICs kept off DHCP auto-profiles ({len(nics)}): {', '.join(sorted(nics))}")
    print(f"\n--- {args.conf_path} ---\n{text}")
    if victims:
        print("Auto-created profiles to delete:")
        for uuid, name, why in victims:
            print(f"  {name} ({why})")
    else:
        print("No auto-created 'Wired connection N' profiles to delete.")
    if args.dry_run:
        print("\nDRY RUN: nothing changed.")
        return 0

    args.conf_path.parent.mkdir(parents=True, exist_ok=True)
    args.conf_path.write_text(text)
    args.conf_path.chmod(0o644)
    run_nmcli(["general", "reload", "conf"])
    for uuid, name, _ in victims:
        run_nmcli(["connection", "delete", "uuid", uuid])
        print(f"deleted {name}")
    print(f"\nInstalled {args.conf_path} and reloaded NetworkManager config.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
