#!/bin/bash

# Script to create udev rules for persistent network interface naming.
# Reads MAC addresses and desired names from config, validates, and generates rules.
# Requires a reboot for names to take effect.

# Color codes
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
NC="\033[0m"  # No Color

# --- Configuration ---
# Get hostname (use -s for short name, adjust if your naming needs FQDN)
HOSTNAME=$(hostname -s)
CONFIG_FILE="./${HOSTNAME}_config.yml"
UDEV_RULES_FILE="/etc/udev/rules.d/10-network-aliases.rules"
# User who invoked sudo, for running yq safely
INVOKING_USER="$SUDO_USER"

# --- Helper Functions ---

# Function to check for required commands
check_dependencies() {
    echo -e "${YELLOW}Checking dependencies...${NC}"
    local missing_deps=0
    local deps=("yq") # Only yq is needed now
    for cmd in "${deps[@]}"; do
        if ! command -v "$cmd" &> /dev/null; then
            echo -e "${RED}Error: Required command '$cmd' not found.${NC}"
            missing_deps=1
        fi
    done
    if [[ "$missing_deps" -eq 0 ]] && ! printf '{}\n' | sudo -u "$INVOKING_USER" yq e '.test' - >/dev/null 2>&1; then
        echo -e "${RED}Error: Installed yq does not support 'yq e' syntax. Run install_yq.sh.${NC}"
        missing_deps=1
    fi
    if [[ "$missing_deps" -eq 1 ]]; then
        echo -e "${RED}Please install missing dependencies and try again.${NC}"
        exit 1
    fi
    echo -e "${GREEN}All dependencies found.${NC}"
}

# Function to safely parse YAML using yq as the invoking user
safe_yq_get() {
    local query=$1
    local file=$2
    sudo -u "$INVOKING_USER" yq e "$query" "$file" 2>/dev/null
    return $? # Return yq's exit code
}

validate_mac_address() {
    local mac=$1
    local valid_mac_regex="^([0-9a-fA-F]{2}[:-]){5}([0-9a-fA-F]{2})$"
    if [[ -z "$mac" || "$mac" == "null" || ! $mac =~ $valid_mac_regex ]]; then
        echo -e "${RED}  Invalid or missing MAC address format: '$mac'${NC}"
        return 1
    fi
    return 0
}

validate_interface_name() {
    local name=$1
    local context=$2 # e.g., "primary name" or "altname"
    # Interface name must be alphanumeric, underscore, hyphen and no longer than 15 characters (IFNAMSIZ)
    local valid_name_regex="^[a-zA-Z0-9_-]{1,15}$"
    if [[ -z "$name" || "$name" == "null" || ! $name =~ $valid_name_regex ]]; then
        echo -e "${RED}  Invalid or missing $context format: '$name' (must be 1-15 alphanumeric/underscore/hyphen chars)${NC}"
        return 1
    fi
    return 0
}

# --- Main Script ---

# Check if running as root
if [[ "$EUID" -ne 0 ]]; then
    echo -e "${RED}Please run as root using sudo${NC}"
    exit 1
fi

# Ensure SUDO_USER is set
if [[ -z "$INVOKING_USER" ]]; then
     echo -e "${RED}Error: Could not determine the original user. Please run using sudo.${NC}"
     exit 1
fi

# Check dependencies first
check_dependencies

# Check if config file exists
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo -e "${RED}Configuration file '$CONFIG_FILE' not found for hostname '$HOSTNAME'.${NC}"
    exit 1
fi
echo -e "${GREEN}Using configuration file: $CONFIG_FILE${NC}"

# Prepare udev rules file
echo -e "${YELLOW}Preparing udev rules file at $UDEV_RULES_FILE...${NC}"
# Create/overwrite the file with a header
cat > "$UDEV_RULES_FILE" << EOF
# Custom udev rules for network interface naming and aliases
# Generated by network_alias_assignment_v2.sh on $(date)
# Based on MAC addresses from $CONFIG_FILE
# Apply rules with: udevadm control --reload-rules && udevadm trigger --action=add --subsystem-match=net
# Or simply reboot the system.

EOF
# Ensure root owns the file and permissions are correct (usually 644)
chown root:root "$UDEV_RULES_FILE"
chmod 644 "$UDEV_RULES_FILE"
echo -e "${GREEN}Initialized $UDEV_RULES_FILE${NC}"


# Parse the number of NICs from the config file
nics_length=$(safe_yq_get '.nics | length' "$CONFIG_FILE")
if ! [[ "$nics_length" =~ ^[0-9]+$ ]]; then
     echo -e "${RED}Error: Could not parse number of NICs from $CONFIG_FILE${NC}"
     exit 1
fi

echo -e "${YELLOW}Generating udev rules...${NC}"
local_errors=0

# Iterate through the nics array
for ((i=0; i<$nics_length; i++)); do
    nic_index_errors=0
    echo -e "${BLUE}Processing NIC definition index: $i${NC}"

    # Get the primary interface name (the key under nics[i])
    nic_name=$(safe_yq_get ".nics[$i] | keys | .[0]" "$CONFIG_FILE")
    if ! validate_interface_name "$nic_name" "primary name"; then
        ((nic_index_errors++))
    fi

    # Extract MAC and altname using the primary name
    mac_address=$(safe_yq_get ".nics[$i].$nic_name.mac_address" "$CONFIG_FILE" | tr '[:upper:]' '[:lower:]') # Ensure lowercase for consistency
    if ! validate_mac_address "$mac_address"; then
        ((nic_index_errors++))
    fi

    altname=$(safe_yq_get ".nics[$i].$nic_name.altname" "$CONFIG_FILE")
    if ! validate_interface_name "$altname" "altname"; then
        ((nic_index_errors++))
    fi

    # Skip writing rules for this NIC if any validation failed
    if [[ "$nic_index_errors" -gt 0 ]]; then
         echo -e "${RED}  Skipping udev rule generation for NIC index $i due to validation errors.${NC}"
         ((local_errors++))
         continue
    fi

    # If validations passed, write the rules
    echo -e "  Adding udev rule for MAC $mac_address -> NAME=$nic_name, SYMLINK+=$altname"
    # Create the primary interface name rule
    echo "SUBSYSTEM==\"net\", ACTION==\"add\", ATTR{address}==\"$mac_address\", NAME=\"$nic_name\"" >> "$UDEV_RULES_FILE"
    # Create symlink for alternative name
    echo "SUBSYSTEM==\"net\", ACTION==\"add\", ATTR{address}==\"$mac_address\", SYMLINK+=\"$altname\"" >> "$UDEV_RULES_FILE"
    echo "" >> "$UDEV_RULES_FILE" # Add a blank line for readability

done # End loop through NICs


# Final status message
if [[ "$local_errors" -gt 0 ]]; then
    echo -e "${YELLOW}Finished generating rules, but $local_errors NIC definition(s) had errors and were skipped.${NC}"
else
    echo -e "${GREEN}Successfully generated all udev rules.${NC}"
fi
echo -e "${GREEN}Network interface naming rules written to $UDEV_RULES_FILE${NC}"

# Prompt for reboot
echo -e "\n${YELLOW}To apply these persistent interface names, the system needs to reload udev rules and re-trigger device events, or be rebooted.${NC}"
echo -e "${YELLOW}A reboot is the simplest way to ensure names are applied correctly before network configuration.${NC}"
echo -e "${YELLOW}Would you like to:${NC}"
echo "1. Save rules and reboot now"
echo "2. Save rules only (manual reboot required)"
read -p "Enter choice (1 or 2): " choice

case $choice in
    1)
        echo -e "${GREEN}Rebooting system...${NC}"
        sync # Ensure all changes are written to disk
        systemctl reboot
        ;;
    2|*) # Default to saving only if choice is not 1
        echo -e "${GREEN}Rules saved to $UDEV_RULES_FILE. Please reboot your system when convenient.${NC}"
        echo -e "${YELLOW}After reboot, run the configure_interfaces_v2.sh script to apply IP settings to the newly named interfaces.${NC}"
        ;;
esac

exit 0
