#!/usr/bin/env python3
"""Per-version, system-wide installs of released recording-transfer sealer wheels.

  install_recording_transfer.sh install 3.0.0 [--wheel PATH]   # verify against releases.json, install (root)
  install_recording_transfer.sh check                          # verify every installed version; exit 1 on drift
  install_recording_transfer.sh list                           # manifest versions and which are installed
  install_recording_transfer.sh uninstall 3.0.0                # remove one version (root)

Layout: <root>/<version>/ is a pip-less venv on /usr/bin/python3 with the wheel unpacked into its
site-packages, console scripts in <root>/<version>/bin/, and INSTALLED.json recording the version,
the wheel sha256, the source tag and the install time. <root> is paths.recording_transfer_root in
the host config (/opt/recording-transfer on pancake0). Root-owned, read-only for everyone else, and
executable by everyone (the domain user that delivers to /groups runs it).

Trust: the wheel must match its releases.json sha256, every file in it must match the wheel's own
RECORD hashes, and it must be a pure-Python wheel. Nothing is fetched from the network. There is no
"current" link: consumers name an exact version directory and pin its sha256.
"""
from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import io
import json
import os
import shutil
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent
MANIFEST = REPO / "packages" / "recording_transfer" / "releases.json"
DEFAULT_ROOT = Path("/opt/recording-transfer")
SYSTEM_PYTHON = "/usr/bin/python3"


class InstallError(Exception):
    pass


def load_manifest(path: Path = MANIFEST) -> dict:
    return json.loads(path.read_text())


def release(manifest: dict, version: str) -> dict:
    for entry in manifest.get("releases", []):
        if entry["version"] == version:
            return entry
    raise InstallError(f"version {version} is not in {MANIFEST.relative_to(REPO)}; add it there first (a reviewed commit)")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def record_digest(data: bytes) -> str:
    return "sha256=" + base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=").decode()


def read_wheel(path: Path) -> tuple[dict[str, bytes], str, dict[str, str]]:
    """(files, dist_info_dir, console_scripts) after checking purity and every RECORD hash."""
    with zipfile.ZipFile(path) as z:
        files = {n: z.read(n) for n in z.namelist() if not n.endswith("/")}
    dist = sorted({n.split("/")[0] for n in files if n.split("/")[0].endswith(".dist-info")})
    if len(dist) != 1:
        raise InstallError(f"{path.name}: expected one .dist-info directory, found {dist}")
    dist_info = dist[0]
    wheel_meta = files.get(f"{dist_info}/WHEEL", b"").decode()
    if "Root-Is-Purelib: true" not in wheel_meta:
        raise InstallError(f"{path.name}: not a pure-Python wheel (Root-Is-Purelib is not true)")
    record = files.get(f"{dist_info}/RECORD")
    if record is None:
        raise InstallError(f"{path.name}: no RECORD")
    listed = {}
    for row in csv.reader(io.StringIO(record.decode())):
        if row:
            listed[row[0]] = row[1] if len(row) > 1 else ""
    for name, data in files.items():
        if name == f"{dist_info}/RECORD":
            continue
        if name not in listed:
            raise InstallError(f"{path.name}: {name} is not listed in RECORD")
        if listed[name] != record_digest(data):
            raise InstallError(f"{path.name}: {name} does not match its RECORD hash")
    for name in listed:
        if name not in files:
            raise InstallError(f"{path.name}: RECORD lists {name}, which the wheel does not contain")
    scripts: dict[str, str] = {}
    entry_points = files.get(f"{dist_info}/entry_points.txt", b"").decode().splitlines()
    section = None
    for line in entry_points:
        line = line.strip()
        if line.startswith("["):
            section = line.strip("[]")
        elif section == "console_scripts" and "=" in line:
            name, target = (x.strip() for x in line.split("=", 1))
            scripts[name] = target
    return files, dist_info, scripts


def script_text(python: Path, target: str) -> str:
    module, _, func = target.partition(":")
    return (f"#!{python}\n# generated by pancakebatter recording_transfer_install.py\nimport sys\n"
            f"from {module} import {func.split('.')[0]}\n"
            f"if __name__ == '__main__':\n    sys.exit({func}())\n")


def install(version: str, wheel: Path, root: Path, manifest: dict, python: str = SYSTEM_PYTHON) -> Path:
    entry = release(manifest, version)
    if not wheel.is_file():
        raise InstallError(f"wheel not found: {wheel}")
    digest = sha256_file(wheel)
    if digest != entry["sha256"]:
        raise InstallError(f"{wheel.name}: sha256 {digest} does not match releases.json {entry['sha256']}")
    files, dist_info, scripts = read_wheel(wheel)
    meta = files[f"{dist_info}/METADATA"].decode()
    if f"\nVersion: {version}\n" not in "\n" + meta:
        raise InstallError(f"{wheel.name}: METADATA does not say Version: {version}")
    final = root / version
    if final.exists():
        raise InstallError(f"{final} already exists; uninstall it first if you mean to replace it")
    root.mkdir(parents=True, exist_ok=True)
    staging = root / f".{version}.staging-{os.getpid()}"
    shutil.rmtree(staging, ignore_errors=True)
    try:
        subprocess.run([python, "-m", "venv", "--without-pip", str(staging)], check=True, capture_output=True, text=True)
        site = next(staging.glob("lib/python3*/site-packages"))
        for name, data in files.items():
            dest = site / name
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
        for junk in staging.glob("bin/[Aa]ctivate*"):   # they embed the staging path; consumers run bin/<script>
            junk.unlink()
        for name, target in scripts.items():
            script = staging / "bin" / name
            script.write_text(script_text(final / "bin" / "python", target))
            script.chmod(0o755)
        (staging / "INSTALLED.json").write_text(json.dumps({
            "package": entry.get("package"), "version": version, "wheel": wheel.name, "wheel_sha256": digest,
            "source": entry.get("source"), "console_scripts": sorted(scripts),
            "installed_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "installed_from": str(wheel), "installer": "pancakebatter/recording_transfer_install.py",
        }, indent=2) + "\n")
        lock_down(staging)
        staging.rename(final)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return final


def lock_down(tree: Path) -> None:
    """Directories 0755, files 0644 (scripts and the venv's interpreters 0755), owned by root when we are root."""
    for path in [tree, *tree.rglob("*")]:
        if path.is_symlink():
            continue
        if os.geteuid() == 0:
            os.chown(path, 0, 0)
        if path.is_dir():
            path.chmod(0o755)
        elif path.parent.name == "bin":
            path.chmod(0o755)
        else:
            path.chmod(0o644)


def verify_install(root: Path, version: str, manifest: dict) -> list[str]:
    """Problems with one installed version (empty = intact)."""
    problems = []
    final = root / version
    receipt = final / "INSTALLED.json"
    try:
        info = json.loads(receipt.read_text())
    except (OSError, ValueError) as exc:
        return [f"{version}: INSTALLED.json unreadable ({exc.__class__.__name__})"]
    try:
        entry = release(manifest, version)
    except InstallError:
        return [f"{version}: installed but not in releases.json"]
    if info.get("version") != version:
        problems.append(f"{version}: INSTALLED.json says version {info.get('version')}")
    if info.get("wheel_sha256") != entry["sha256"]:
        problems.append(f"{version}: installed wheel sha256 {info.get('wheel_sha256')} differs from releases.json")
    sites = list(final.glob("lib/python3*/site-packages"))
    records = list(sites[0].glob("*.dist-info/RECORD")) if sites else []
    if not records:
        problems.append(f"{version}: no RECORD under site-packages")
    else:
        for row in csv.reader(io.StringIO(records[0].read_text())):
            if not row or not row[1]:
                continue
            path = sites[0] / row[0]
            if not path.is_file():
                problems.append(f"{version}: {row[0]} is missing")
            elif record_digest(path.read_bytes()) != row[1]:
                problems.append(f"{version}: {row[0]} was modified after install")
    for name in info.get("console_scripts", []):
        script = final / "bin" / name
        if not (script.is_file() and os.access(script, os.X_OK)):
            problems.append(f"{version}: console script {name} missing or not executable")
    if os.geteuid() != 0 and os.access(final, os.W_OK) and final.stat().st_uid == 0:
        problems.append(f"{version}: {final} is writable by this user")
    return problems


def installed_versions(root: Path) -> list[str]:
    if not root.is_dir():
        return []
    return sorted(p.name for p in root.iterdir() if p.is_dir() and not p.name.startswith(".") and (p / "INSTALLED.json").exists())


def uninstall(version: str, root: Path) -> None:
    final = root / version
    if not (final / "INSTALLED.json").exists():
        raise InstallError(f"{final} is not an installed version")
    shutil.rmtree(final)


def default_root() -> Path:
    try:
        import yaml
        import hostconfig
        cfg = yaml.safe_load(hostconfig.default_config_path().read_text()) or {}
        value = (cfg.get("paths") or {}).get("recording_transfer_root")
        if value:
            return Path(value)
    except Exception:
        pass
    return DEFAULT_ROOT


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], epilog=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, help="install root (default: paths.recording_transfer_root, else /opt/recording-transfer)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("install")
    p.add_argument("version")
    p.add_argument("--wheel", type=Path, help="wheel file (default: <wheel_dir>/<wheel> from releases.json)")
    p = sub.add_parser("uninstall")
    p.add_argument("version")
    sub.add_parser("check")
    sub.add_parser("list")
    args = ap.parse_args(argv)
    root = args.root or default_root()
    manifest = load_manifest()
    try:
        if args.cmd == "install":
            entry = release(manifest, args.version)
            wheel = args.wheel or Path(manifest.get("wheel_dir", ".")) / entry["wheel"]
            final = install(args.version, wheel, root, manifest)
            print(f"installed {entry.get('package')} {args.version} at {final} (wheel sha256 {entry['sha256']})")
            for name in json.loads((final / "INSTALLED.json").read_text())["console_scripts"]:
                print(f"  {final / 'bin' / name}")
            return 0
        if args.cmd == "uninstall":
            uninstall(args.version, root)
            print(f"removed {root / args.version}")
            return 0
        if args.cmd == "list":
            have = set(installed_versions(root))
            for entry in manifest["releases"]:
                print(f"{entry['version']:10s} {'installed' if entry['version'] in have else 'not installed':14s} {entry['sha256'][:16]}...  {entry['source'].get('tag')}")
            return 0
        problems = []
        versions = installed_versions(root)
        for version in versions:
            problems += verify_install(root, version, manifest)
        for p in problems:
            print(f"[FAIL] {p}")
        print(f"recording-transfer installs under {root}: {', '.join(versions) or 'none'}; "
              f"{'PASS' if not problems else 'FAIL'} ({len(problems)} problems)")
        return 1 if problems else 0
    except InstallError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
