# pancake0 configuration file
# Establishes versions of drivers, types of onboard hardware expected,
# etc...

# System Information: OS, Kernel, ESDK, CUDA, FFmpeg, OpenCV, TensorRT, NVIDIA Driver, CUDA Capability
system_info:
  hostname: pancake0
  ubuntu_version: "22.04"
  kernel_version: 6.5.0-44-generic
  esdk_version: "1.0"
  cuda_version: "12.2.140"
  ffmpeg_version: "4.4"
  opencv_version: "4.8.0"
  tensorrt_version: "10.0.1.6"
  nvidia_driver_version: "535.183.06"
  cuda_capability: "sm_86"

# GPUs
gpus:
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA RTX A6000
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06
  - model: NVIDIA A16
    driver_version: 535.183.06

nics:
  - mlnx2_p1_25g:
    mac_address: b8:ce:f6:22:09:76
    brand: Mellanox
    model: MT27800 Family [ConnectX-5]
    subsystem: ConnectX-5 EN network interface card, 10/25GbE dual-port SFP28, PCIe3.0 x8, tall bracket ; MCX512A-ACAT
    pcie_id: 49:00.0
    mtu: 9000
    ip_address: 192.168.130.1/24
    camera: camera3
    link_settings:
      speed: 25000
      autoneg: false
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLBS0450180
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

  - mlnx2_p2_25g:
    mac_address: b8:ce:f6:22:09:77
    brand: Mellanox
    model: MT27800 Family [ConnectX-5]
    subsystem: ConnectX-5 EN network interface card, 10/25GbE dual-port SFP28, PCIe3.0 x8, tall bracket ; MCX512A-ACAT
    pcie_id: 49:00.1
    mtu: 9000
    ip_address: 192.168.140.1/24
    camera: camera4
    link_settings:
      speed: 25000
      autoneg: false
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLAK1610003
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

  - mlnx1_p1_25g:
    mac_address: 10:70:fd:5e:5c:28
    brand: Mellanox
    model: MT27800 Family [ConnectX-5]
    subsystem: ConnectX-5 EN network interface card, 10/25GbE dual-port SFP28, PCIe3.0 x8, tall bracket ; MCX512A-ACAT
    pcie_id: 61:00.0
    mtu: 9000
    ip_address: 192.168.110.1/24
    camera: camera1
    link_settings:
      speed: 25000
      autoneg: false
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLAK1610002 
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

  - mlnx1_p2_25g:
    mac_address: 10:70:fd:5e:5c:29
    brand: Mellanox
    model: MT27800 Family [ConnectX-5]
    subsystem: ConnectX-5 EN network interface card, 10/25GbE dual-port SFP28, PCIe3.0 x8, tall bracket ; MCX512A-ACAT
    pcie_id: 61:00.1 
    mtu: 9000
    ip_address: 192.168.120.1/24
    camera: camera2
    link_settings:
      speed: 25000
      autoneg: false
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLBS0450179  # Updated from ethtool output
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

# Cameras: Primary key is MAC address of machine
cameras:
  E0-55-97-1E-AB-ED:
    model: HB-20000-SB-M-E2
    serial_number: 02010093
    ip_address: 192.168.110.2
    nic_port: mlnx1_p1_25g
    interface: 25GigE SFP28
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLBO0680127
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF
    sensor:
      brand: Sony Pregius S
      model: IMX530
      mp_resolution: 20.28
      x_resolution: 4504
      y_resolution: 4504
      cell_size: 2.74
      sensor_type: CMOS
      sensor_size: 1.1
      shutter: Global
      max_exposure: 1
      min_exposure: 0.000005
      bit_depth:
        - 8
        - 12
      gpio_in: 3
      gpio_out: 3
      monochrome_modes:
        - Mono8
        - Mono12
        - Mono12Packed
      raw_modes:
        - BayerRG8
        - BayerRG12
        - BayerRG12Packed
      compliance:
        - CE
        - FCC
        - RoHS
        - WEEE
        - GigE Vision
        - GenICam
      power_requirements:
        - 9W
        - 12V
      storage_temperature:
        - -30
        - 60
      operating_temperature:
        - 0
        - 45
      dimensions:
        - 97
        - 66
        - 52
      weight: 500

  E0-55-97-1E-AB-EE:
    model: HB-20000-SB-M-E2
    serial_number: 002010094
    ip_address: 192.168.120.2
    nic_port: mlnx1_p2_25g
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLBS045088
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

  E0-55-97-1E-AB-EF:
    model: HB-20000-SB-M-E2
    serial_number: 02010095
    ip_address: 192.168.130.2
    nic_port: mlnx2_p1_25g
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLAK1610081
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

  E0-55-97-1E-AB-F0:
    model: HB-20000-SB-M-E2
    serial_number: 02010096
    ip_address: 192.168.140.2
    nic_port: mlnx2_p2_25g
    transceiver:
      brand: InnoLight
      model: TR-PY13L-V00
      serial_number: INLBS0450134
      speed: 25
      wavelength: 1310
      max_distance: 10
      fiber_type: SMF

# PCIe Slots: E = Empty
# | E | NVIDIA RTX A6000 | Mellanox MCX512A-ACAT | Mellanox MCX512A-ACAT | NVIDIA A16 | NVIDIA A16 |
# | - | ---------------- | --------------------- | --------------------- | ---------- | ---------- |
# |   | Display          | 25Gbps, 2 Ports       |  25 Gbps, 2 Ports     | 4 GPUs     | 4 GPUs     |